name: SuperCloudys
options:
  bundleIdPrefix: com.yeshan333
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  SuperCloudys:
    type: application
    platform: macOS
    sources:
      - path: SuperCloudys
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeshan333.SuperCloudys
        INFOPLIST_FILE: SuperCloudys/Info.plist
        CODE_SIGN_ENTITLEMENTS: SuperCloudys/SuperCloudys.entitlements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - target: SuperCloudysExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins

  SuperCloudysExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: SuperCloudysExtension
        excludes:
          - "**/*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeshan333.SuperCloudys.FinderSyncExtension
        INFOPLIST_FILE: SuperCloudysExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: SuperCloudysExtension/SuperCloudysExtension.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../../../../../Frameworks"
    frameworks:
      - sdk: FinderSync.framework

  SuperCloudysTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SuperCloudysTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeshan333.SuperCloudysTests
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SuperCloudys.app/Contents/MacOS/SuperCloudys"
    dependencies:
      - target: SuperCloudys
