import AppKit
import ImageIO
import os

protocol ClipboardMonitorDelegate: AnyObject {
    func clipboardMonitor(
        _ monitor: ClipboardMonitorService,
        didCapture entry: ClipboardEntry,
        generation: Int
    )
}

final class ClipboardMonitorService {

    weak var delegate: ClipboardMonitorDelegate?

    private let pasteboard = NSPasteboard.general
    private let log = Logger(subsystem: "com.yeshan333.SuperCloudys", category: "ClipboardMonitor")
    private let pollQueue = DispatchQueue(label: "com.yeshan333.SuperCloudys.clipboardPoll", qos: .utility)
    private var timer: DispatchSourceTimer?
    private let stateLock = NSLock()
    private var generation = 0
    private var lastChangeCount: Int
    private let suppressionLock = NSLock()
    private var suppressedChangeRange: ClosedRange<Int>?
    private let settings: ClipboardSettings
    private var lastFrontmostBundleID: String?
    private var previousFrontmostBundleID: String?
    private var frontmostChangedAt = Date.distantPast
    var assetsDirectory: URL?

    private static let maxTextBytes = 2 * 1024 * 1024
    private static let maxImagePixels: Int64 = 50_000_000
    private static let maxImageBytes = 100 * 1024 * 1024

    init(settings: ClipboardSettings = .shared) {
        self.settings = settings
        self.lastChangeCount = pasteboard.changeCount
        self.lastFrontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    func start() {
        stateLock.lock()
        defer { stateLock.unlock() }
        guard timer == nil else { return }
        generation += 1
        let captureGeneration = generation
        let t = DispatchSource.makeTimerSource(queue: pollQueue)
        t.schedule(deadline: .now(), repeating: 0.5)
        t.setEventHandler { [weak self] in
            self?.poll(generation: captureGeneration)
        }
        t.resume()
        timer = t
        log.info("Clipboard monitor started")
    }

    func stop() {
        stateLock.lock()
        defer { stateLock.unlock() }
        generation += 1
        timer?.cancel()
        timer = nil
        log.info("Clipboard monitor stopped")
    }

    func markSelfWrite(changeCount: Int) {
        suppressionLock.lock()
        suppressedChangeRange = changeCount...changeCount
        suppressionLock.unlock()
    }

    func performSelfWrite(_ operation: () -> Bool) -> Bool {
        suppressionLock.lock()
        defer { suppressionLock.unlock() }

        let start = pasteboard.changeCount
        let success = operation()
        let end = pasteboard.changeCount
        if end > start {
            suppressedChangeRange = (start + 1)...end
        }
        return success
    }

    // MARK: - Private

    private func poll(generation: Int) {
        guard isCaptureValid(generation) else { return }
        let sourceApp = NSWorkspace.shared.frontmostApplication
        let sourceBundleID = sourceApp?.bundleIdentifier
        let now = Date()
        if sourceBundleID != lastFrontmostBundleID {
            previousFrontmostBundleID = lastFrontmostBundleID
            lastFrontmostBundleID = sourceBundleID
            frontmostChangedAt = now
        }

        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        defer { lastChangeCount = current }

        if consumeSuppressedChangeCount(current) { return }

        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }

        let sourceAppName = sourceApp?.localizedName

        if shouldExclude(
            sourceBundleID: sourceBundleID,
            previousBundleID: previousFrontmostBundleID,
            secondsSinceSwitch: now.timeIntervalSince(frontmostChangedAt)
        ) {
            return
        }

        if hasTransientTypes(items) {
            return
        }

        guard let entry = decode(sourceBundleID: sourceBundleID, sourceAppName: sourceAppName) else {
            return
        }

        delegate?.clipboardMonitor(self, didCapture: entry, generation: generation)
    }

    func isCaptureValid(_ captureGeneration: Int) -> Bool {
        stateLock.lock()
        defer { stateLock.unlock() }
        return timer != nil && generation == captureGeneration
    }

    func shouldExclude(
        sourceBundleID: String?,
        previousBundleID: String?,
        secondsSinceSwitch: TimeInterval
    ) -> Bool {
        if let sourceBundleID, settings.isAppExcluded(sourceBundleID) { return true }
        // ponytail: one polling interval of false positives is safer than storing a switched-away password.
        return secondsSinceSwitch < 0.75
            && previousBundleID.map(settings.isAppExcluded) == true
    }

    private func hasTransientTypes(_ items: [NSPasteboardItem]) -> Bool {
        let transientTypes: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]
        for item in items {
            for type in item.types {
                if transientTypes.contains(type.rawValue) {
                    return true
                }
            }
        }
        return false
    }

    private func decode(
        sourceBundleID: String?,
        sourceAppName: String?
    ) -> ClipboardEntry? {
        // Try URL first (non-file)
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
            let webURLs = urls.filter { !$0.isFileURL }
            if let url = webURLs.first {
                return makeEntry(
                    type: .url,
                    plainText: url.absoluteString,
                    title: url.absoluteString,
                    sourceBundleID: sourceBundleID,
                    sourceAppName: sourceAppName
                )
            }
            let fileURLs = urls.filter { $0.isFileURL }
            if !fileURLs.isEmpty {
                let paths = fileURLs.map(\.path)
                let title = fileURLs.count == 1
                    ? (fileURLs.first?.lastPathComponent ?? "文件")
                    : "\(fileURLs.count) 个文件"
                return makeEntry(
                    type: .fileGroup,
                    plainText: paths.joined(separator: "\n"),
                    title: title,
                    sourceBundleID: sourceBundleID,
                    sourceAppName: sourceAppName,
                    filePaths: paths
                )
            }
        }

        // Try color
        if let colors = pasteboard.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
           let color = colors.first {
            let hex = colorToHex(color)
            return makeEntry(
                type: .color,
                plainText: hex,
                title: hex,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                colorHex: hex
            )
        }

        // Prefer encoded image data so large images are not decoded just to be stored again.
        let imagePayload: (data: Data, fileExtension: String)? = {
            if let data = pasteboard.data(forType: .png) { return (data, "png") }
            if let data = pasteboard.data(forType: .tiff) { return (data, "tiff") }
            guard let image = (pasteboard.readObjects(
                forClasses: [NSImage.self], options: nil
            ) as? [NSImage])?.first,
                  let data = image.tiffRepresentation else { return nil }
            return (data, "tiff")
        }()
        if let imagePayload {
            guard let saved = saveImageData(
                imagePayload.data,
                fileExtension: imagePayload.fileExtension
            ) else { return nil }
            return makeEntry(
                type: .image,
                plainText: nil,
                title: "图片 \(saved.width)×\(saved.height)",
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                imagePath: saved.original,
                thumbnailPath: saved.thumbnail,
                fingerprint: saved.fingerprint
            )
        }

        // Try text (richText check via RTF presence)
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            guard text.utf8.count <= Self.maxTextBytes else {
                log.warning("Skipped clipboard text larger than \(Self.maxTextBytes) bytes")
                return nil
            }
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            // ponytail: rich text was never restored; keep new entries honest and store plain text.
            let type: ClipboardContentType = detectedWebURL(in: trimmed) != nil ? .url : .text
            let title = trimmed.isEmpty ? "空白文本" : String(trimmed.prefix(100))
            return makeEntry(
                type: type,
                plainText: text,
                title: title,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName
            )
        }

        return nil
    }

    func detectedWebURL(in text: String) -> URL? {
        guard !text.isEmpty else { return nil }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue),
              let match = detector.firstMatch(in: text, options: [], range: range),
              match.range == range,
              let url = match.url,
              !url.isFileURL,
              let scheme = url.scheme?.lowercased(),
              ["http", "https", "ftp", "ftps", "mailto", "ws", "wss"].contains(scheme) else {
            return nil
        }
        return url
    }

    private func makeEntry(
        type: ClipboardContentType,
        plainText: String?,
        title: String,
        sourceBundleID: String?,
        sourceAppName: String?,
        filePaths: [String]? = nil,
        colorHex: String? = nil,
        imagePath: String? = nil,
        thumbnailPath: String? = nil,
        fingerprint: String? = nil
    ) -> ClipboardEntry {
        ClipboardEntry(
            id: UUID(),
            contentType: type,
            plainText: plainText,
            title: title,
            subtitle: sourceAppName,
            createdAt: Date(),
            sourceAppBundleID: sourceBundleID,
            sourceAppName: sourceAppName,
            isPinned: false,
            lastUsedAt: nil,
            fingerprint: fingerprint ?? ClipboardEntry.fingerprint(type: type, content: plainText ?? imagePath),
            imagePath: imagePath,
            thumbnailPath: thumbnailPath,
            filePaths: filePaths,
            colorHex: colorHex
        )
    }

    private func saveImageData(
        _ data: Data,
        fileExtension: String
    ) -> (original: String, thumbnail: String?, fingerprint: String, width: Int, height: Int)? {
        guard let dir = assetsDirectory else { return nil }
        return autoreleasepool {
            guard data.count <= Self.maxImageBytes else {
                log.warning("Skipped clipboard image larger than \(Self.maxImageBytes) bytes")
                return nil
            }
            guard let source = CGImageSourceCreateWithData(data as CFData, nil),
                  let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil)
                    as? [CFString: Any],
                  let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
                  let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
                  width > 0, height > 0 else { return nil }
            let (pixelCount, overflow) = Int64(width).multipliedReportingOverflow(
                by: Int64(height)
            )
            guard !overflow, pixelCount <= Self.maxImagePixels else {
                log.warning("Skipped clipboard image with \(pixelCount) pixels")
                return nil
            }
            let fingerprint = ClipboardEntry.fingerprint(type: .image, data: data)

            let id = UUID().uuidString
            let originalURL = dir.appendingPathComponent("\(id).\(fileExtension)")
            let thumbURL = dir.appendingPathComponent("\(id)_thumb.png")

            do {
                try data.write(to: originalURL, options: .atomic)
                restrictPermissions(for: originalURL)
            } catch {
                log.error("Cannot save clipboard image: \(error.localizedDescription, privacy: .public)")
                return nil
            }

            var thumbnailPath: String?
            if max(width, height) > 320,
               let thumbCG = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                   kCGImageSourceCreateThumbnailFromImageAlways: true,
                   kCGImageSourceCreateThumbnailWithTransform: true,
                   kCGImageSourceThumbnailMaxPixelSize: 320
               ] as CFDictionary),
               let thumbPng = NSBitmapImageRep(cgImage: thumbCG)
                   .representation(using: .png, properties: [:]) {
                do {
                    try thumbPng.write(to: thumbURL, options: .atomic)
                    restrictPermissions(for: thumbURL)
                    thumbnailPath = thumbURL.path
                } catch {
                    log.error("Cannot save clipboard thumbnail: \(error.localizedDescription, privacy: .public)")
                }
            }

            return (
                originalURL.path,
                thumbnailPath,
                fingerprint,
                width,
                height
            )
        }
    }

    func consumeSuppressedChangeCount(_ current: Int) -> Bool {
        suppressionLock.lock()
        defer { suppressionLock.unlock() }
        guard let range = suppressedChangeRange else { return false }
        if current <= range.upperBound {
            if current == range.upperBound { suppressedChangeRange = nil }
            return true
        }
        suppressedChangeRange = nil
        return false
    }

    private func colorToHex(_ color: NSColor) -> String {
        guard let rgb = color.usingColorSpace(.sRGB) else { return "#000000" }
        let r = Int(rgb.redComponent * 255)
        let g = Int(rgb.greenComponent * 255)
        let b = Int(rgb.blueComponent * 255)
        let a = Int(rgb.alphaComponent * 255)
        return a < 255
            ? String(format: "#%02X%02X%02X%02X", r, g, b, a)
            : String(format: "#%02X%02X%02X", r, g, b)
    }

    private func restrictPermissions(for url: URL) {
        do {
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o600],
                ofItemAtPath: url.path
            )
        } catch {
            log.warning("Cannot restrict clipboard image permissions: \(error.localizedDescription, privacy: .public)")
        }
    }
}
