import AppKit
import os

protocol ClipboardMonitorDelegate: AnyObject {
    func clipboardMonitor(_ monitor: ClipboardMonitorService, didCapture entry: ClipboardEntry)
}

final class ClipboardMonitorService {

    weak var delegate: ClipboardMonitorDelegate?

    private let pasteboard = NSPasteboard.general
    private let log = Logger(subsystem: "com.yeshan333.SuperCloudys", category: "ClipboardMonitor")
    private var timer: Timer?
    private var lastChangeCount: Int
    private var suppressUntil: Date?
    private let settings: ClipboardSettings
    var assetsDirectory: URL?

    init(settings: ClipboardSettings = .shared) {
        self.settings = settings
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(
            withTimeInterval: 0.5, repeats: true
        ) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer!, forMode: .common)
        log.info("Clipboard monitor started")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        log.info("Clipboard monitor stopped")
    }

    func markSelfWrite() {
        suppressUntil = Date().addingTimeInterval(1.0)
    }

    // MARK: - Private

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        defer { lastChangeCount = current }

        if let until = suppressUntil, Date() < until {
            return
        }
        suppressUntil = nil

        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let sourceBundleID = sourceApp?.bundleIdentifier
        let sourceAppName = sourceApp?.localizedName

        if let bundleID = sourceBundleID, settings.isAppExcluded(bundleID) {
            return
        }

        if hasTransientTypes(items) {
            return
        }

        guard let entry = decode(items: items, sourceBundleID: sourceBundleID, sourceAppName: sourceAppName) else {
            return
        }

        delegate?.clipboardMonitor(self, didCapture: entry)
    }

    private func hasTransientTypes(_ items: [NSPasteboardItem]) -> Bool {
        let transientTypes: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]
        for item in items {
            for type in item.types {
                if transientTypes.contains(type.rawValue) {
                    return true
                }
            }
        }
        return false
    }

    private func decode(
        items: [NSPasteboardItem],
        sourceBundleID: String?,
        sourceAppName: String?
    ) -> ClipboardEntry? {
        // Try URL first (non-file)
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
            let webURLs = urls.filter { !$0.isFileURL }
            if let url = webURLs.first {
                return makeEntry(
                    type: .url,
                    plainText: url.absoluteString,
                    title: url.absoluteString,
                    sourceBundleID: sourceBundleID,
                    sourceAppName: sourceAppName
                )
            }
            let fileURLs = urls.filter { $0.isFileURL }
            if !fileURLs.isEmpty {
                let paths = fileURLs.map(\.path)
                let title = fileURLs.count == 1
                    ? (fileURLs.first?.lastPathComponent ?? "File")
                    : "\(fileURLs.count) files"
                return makeEntry(
                    type: .fileGroup,
                    plainText: paths.joined(separator: "\n"),
                    title: title,
                    sourceBundleID: sourceBundleID,
                    sourceAppName: sourceAppName,
                    filePaths: paths
                )
            }
        }

        // Try color
        if let colors = pasteboard.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
           let color = colors.first {
            let hex = colorToHex(color)
            return makeEntry(
                type: .color,
                plainText: hex,
                title: hex,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                colorHex: hex
            )
        }

        // Try image
        if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = images.first {
            let title = imageSizeDescription(image)
            let paths = saveImage(image)
            return makeEntry(
                type: .image,
                plainText: nil,
                title: title,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                imagePath: paths.original,
                thumbnailPath: paths.thumbnail
            )
        }

        // Try text (richText check via RTF presence)
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let hasRTF = pasteboard.data(forType: .rtf) != nil
            let type: ClipboardContentType = hasRTF ? .richText : .text
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            let title = String(trimmed.prefix(100))
            return makeEntry(
                type: type,
                plainText: text,
                title: title,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName
            )
        }

        return nil
    }

    private func makeEntry(
        type: ClipboardContentType,
        plainText: String?,
        title: String,
        sourceBundleID: String?,
        sourceAppName: String?,
        filePaths: [String]? = nil,
        colorHex: String? = nil,
        imagePath: String? = nil,
        thumbnailPath: String? = nil
    ) -> ClipboardEntry {
        ClipboardEntry(
            id: UUID(),
            contentType: type,
            plainText: plainText,
            title: title,
            subtitle: sourceAppName,
            createdAt: Date(),
            sourceAppBundleID: sourceBundleID,
            sourceAppName: sourceAppName,
            isPinned: false,
            lastUsedAt: nil,
            fingerprint: ClipboardEntry.fingerprint(type: type, content: plainText ?? imagePath),
            imagePath: imagePath,
            thumbnailPath: thumbnailPath,
            filePaths: filePaths,
            colorHex: colorHex
        )
    }

    private static let imageQueue = DispatchQueue(label: "com.yeshan333.SuperCloudys.imageSave")

    private func saveImage(_ image: NSImage) -> (original: String?, thumbnail: String?) {
        guard let dir = assetsDirectory else { return (nil, nil) }
        let id = UUID().uuidString
        let originalURL = dir.appendingPathComponent("\(id).png")
        let thumbURL = dir.appendingPathComponent("\(id)_thumb.png")

        guard let tiffData = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData),
              let pngData = bitmap.representation(using: .png, properties: [:]) else {
            return (nil, nil)
        }

        // Write original synchronously so paths are valid immediately
        try? pngData.write(to: originalURL)

        // Generate thumbnail on background using Core Graphics (thread-safe)
        let imageSize = image.size
        Self.imageQueue.async {
            let thumbMaxDim: CGFloat = 320
            let scale = min(thumbMaxDim / imageSize.width, thumbMaxDim / imageSize.height, 1.0)
            let w = Int(imageSize.width * scale)
            let h = Int(imageSize.height * scale)

            guard let cgImage = bitmap.cgImage,
                  let ctx = CGContext(
                      data: nil, width: w, height: h,
                      bitsPerComponent: 8, bytesPerRow: 0,
                      space: CGColorSpaceCreateDeviceRGB(),
                      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
                  ) else { return }

            ctx.interpolationQuality = .high
            ctx.draw(cgImage, in: CGRect(x: 0, y: 0, width: w, height: h))
            guard let thumbCG = ctx.makeImage() else { return }

            let thumbRep = NSBitmapImageRep(cgImage: thumbCG)
            if let thumbPng = thumbRep.representation(using: .png, properties: [:]) {
                try? thumbPng.write(to: thumbURL)
            }
        }

        return (originalURL.path, thumbURL.path)
    }

    private func colorToHex(_ color: NSColor) -> String {
        guard let rgb = color.usingColorSpace(.sRGB) else { return "#000000" }
        let r = Int(rgb.redComponent * 255)
        let g = Int(rgb.greenComponent * 255)
        let b = Int(rgb.blueComponent * 255)
        return String(format: "#%02X%02X%02X", r, g, b)
    }

    private func imageSizeDescription(_ image: NSImage) -> String {
        let size = image.size
        return "Image \(Int(size.width))×\(Int(size.height))"
    }
}
